import Link from "next/link";
import { Button } from "@/components/ui/button";

export const metadata = { title: "Terms of Use — Mapleins" };

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">

      {/* Header */}
      <header className="border-b border-gray-100 sticky top-0 bg-white z-50">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between">
          <Link href="/" className="text-2xl font-bold text-[#166534] shrink-0">Mapleins</Link>
          <nav className="hidden md:flex items-center gap-1 text-sm font-medium">
            <Link href="/"        className="px-3 py-2 rounded-md text-gray-700 hover:text-[#166534] hover:bg-green-50 transition-colors">Home</Link>
            <Link href="/about"   className="px-3 py-2 rounded-md text-gray-700 hover:text-[#166534] hover:bg-green-50 transition-colors">Our Story</Link>
            <Link href="/blog"    className="px-3 py-2 rounded-md text-gray-700 hover:text-[#166534] hover:bg-green-50 transition-colors">Blog</Link>
            <Link href="/contact" className="px-3 py-2 rounded-md text-gray-700 hover:text-[#166534] hover:bg-green-50 transition-colors">Contact</Link>
          </nav>
          <div className="flex items-center gap-3">
            <Link href="/login" className="text-sm font-medium text-gray-700 hover:text-[#166534] px-3 py-2 rounded-md hover:bg-green-50 transition-colors hidden md:inline">Sign in</Link>
            <Link href="/signup">
              <Button className="bg-[#166534] hover:bg-[#15803d] text-white">Get Started →</Button>
            </Link>
          </div>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-16">

        <div className="mb-10">
          <span className="text-sm font-semibold text-[#166534] uppercase tracking-widest">Legal</span>
          <h1 className="mt-3 text-4xl font-bold text-gray-900">Terms of Use</h1>
          <p className="mt-3 text-sm text-gray-500">Last updated: {new Date().getFullYear()}</p>
        </div>

        <div className="prose prose-gray max-w-none space-y-8 text-gray-700 leading-relaxed">

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">1. Acceptance</h2>
            <p>
              By creating an account or using Mapleins (&quot;the Service&quot;), you agree to these Terms of Use.
              If you do not agree, please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">2. What Mapleins provides</h2>
            <p>
              Mapleins provides AI-powered resume analysis and optimisation tools intended to help job seekers
              in the Canadian market. The output is generated by artificial intelligence and is provided as-is.
              We do not guarantee employment outcomes, interview invitations, or job offers.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">3. Your responsibilities</h2>
            <p>You agree to:</p>
            <ul className="list-disc list-inside mt-2 space-y-1 text-gray-600">
              <li>Provide accurate information about yourself and your work history</li>
              <li>Use the Service only for lawful, personal job-search purposes</li>
              <li>Not attempt to reverse-engineer, scrape, or misuse the Service</li>
              <li>Not upload content that is fraudulent, harmful, or violates third-party rights</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">4. Donations</h2>
            <p>
              Donations are voluntary and non-refundable. They are used to cover operating costs and are not
              exchanged for any product, service guarantee, or premium feature. Mapleins remains free for all users
              regardless of whether a donation is made.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">5. Intellectual property</h2>
            <p>
              The Mapleins brand, code, and design are owned by Mapleins. The content of your resume remains
              yours. By uploading your resume, you grant Mapleins a limited licence to process it for the
              purpose of providing the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">6. Disclaimers</h2>
            <p>
              The Service is provided &quot;as is&quot; without warranties of any kind. Mapleins is not responsible for
              decisions made by employers based on resumes generated by the Service. AI output may contain errors
              and should be reviewed carefully before use.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">7. Limitation of liability</h2>
            <p>
              To the maximum extent permitted by law, Mapleins shall not be liable for any indirect, incidental,
              or consequential damages arising from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">8. Changes</h2>
            <p>
              We may update these terms from time to time. Continued use of the Service after changes are posted
              constitutes acceptance of the revised terms. Material changes will be communicated by email.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">9. Contact</h2>
            <p>
              Questions about these terms? Email{" "}
              <a href="mailto:hello@mapleins.ca" className="text-[#166534] hover:underline">hello@mapleins.ca</a>{" "}
              or use our <Link href="/contact" className="text-[#166534] hover:underline">contact form</Link>.
            </p>
          </section>

        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-200 py-6 mt-4">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 flex flex-col sm:flex-row justify-between items-center gap-3 text-sm text-gray-600 font-medium">
          <span>© {new Date().getFullYear()} Mapleins</span>
          <div className="flex gap-6">
            <Link href="/"        className="hover:text-[#166534] transition-colors">Home</Link>
            <Link href="/privacy" className="hover:text-[#166534] transition-colors">Privacy Policy</Link>
            <Link href="/contact" className="hover:text-[#166534] transition-colors">Contact</Link>
          </div>
        </div>
      </footer>

    </div>
  );
}
